=== wachub/neuron4/neuroConstruct/templates/xmlTemplates/CellProcessPlot.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>


    <!-- This XML Schema describes how to specify "interesting" plots related to Cell Process in neuroConstruct
         See included examples for usage. Note that this specification is quite likely to change as the Cell Processes
         themselves become more XML friendly... -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/"
        xmlns="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/"
        elementFormDefault="qualified">

    <xs:element name="plotlist">

        <xs:complexType>
            <xs:sequence>

                <xs:element name="parameter"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parametername" type="xs:string"/>
                            <xs:element name="symbol" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="plot"   maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plotname" type="xs:string"/>
                            <xs:element name="independentvariable" type="xs:string"/>
                            <xs:element name="maxvalue" type="xs:decimal"/>
                            <xs:element name="minvalue" type="xs:decimal"/>
                            <xs:element name="expression" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>

=== wachub/neuron4/neuroConstruct/templates/xmlTemplates/DoubExpSynPlots.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

  
<plotlist xmlns="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
          xsi:schemaLocation="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/ CellProcessPlot.xsd">
    
    <parameter>
        <parametername>Tau Rise</parametername>
        <symbol>t1</symbol>
    </parameter>
    
    <parameter>
        <parametername>Tau Decay</parametername>
        <symbol>t2</symbol>
    </parameter>
    
    <parameter>
        <parametername>Max Conductance</parametername>
        <symbol>gmax</symbol>
    </parameter>
        
    <plot>
        <plotname>Rise and fall</plotname>
        <independentvariable>t</independentvariable>
        <maxvalue>10</maxvalue>
        <minvalue>0</minvalue>
        <expression>exp(-t/t2)-exp(-t/t1)</expression>
    </plot>  
    
    <plot>
        <plotname>Decay only</plotname>
        <independentvariable>t</independentvariable>
        <maxvalue>10</maxvalue>
        <minvalue>0</minvalue>
        <expression>exp(-t/t2)</expression>
    </plot>    
    
    
</plotlist>

=== wachub/neuron4/neuroConstruct/templates/xmlTemplates/PassiveCondPlots.xml
<?xml version="1.0" encoding="ISO-8859-1"?>


<plotlist xmlns="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.physiol.ucl.ac.uk/research/silver_a/neuroConstruct/ CellProcessPlot.xsd">


    <parameter>
        <parametername>Max Conductance Density</parametername>
        <symbol>gmax</symbol>
    </parameter>

    <parameter>
        <parametername>Reversal Potential</parametername>
        <symbol>e</symbol>
    </parameter>

    <plot>
        <plotname>Current out of cell</plotname>
        <independentvariable>v</independentvariable>
        <maxvalue>100</maxvalue>
        <minvalue>-100</minvalue>
        <expression>gbar * (v-e)</expression>
    </plot>


</plotlist>
