=== wachub/neuron4/neuroConstruct/templates/xmlTemplates/ChannelMLMetadata.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>


<!--
     This XML Schema describes how to create XML files giving additional data
     on ChannelML files. Aliases can be assigned for the more useful data fields
     for easier access. Functions of the parameters in the channels can be
     described so that relevant plots can be generated

     NOTE: This is not part of the official ChannelML spec. It's just to help neuroConstruct
     create a more user friendly view of the data in the XML file.
 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.neuroConstruct.org"
        xmlns="http://www.neuroConstruct.org"
        elementFormDefault="qualified">

    <xs:element name="cmlmetadata">

        <xs:complexType>
            <xs:sequence>

                <xs:element name="parameter"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameterpath" type="xs:string"/>
                            <xs:element name="alias" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>



                <xs:element name="plot"   maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plotname" type="xs:string"/>
                            <xs:element name="independentvariable" type="xs:string"/>
                            <xs:element name="maxvalue" type="xs:decimal"/>
                            <xs:element name="minvalue" type="xs:decimal"/>
                            <xs:element name="expression" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>

=== wachub/neuron4/neuroConstruct/templates/xmlTemplates/LeakCondMetadata.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
     This is a ChannelML Metadata file. It gives some additional information on
     a particular type of channel mechanism described in ChannelML format.

     NOTE: This is not part of the official ChannelML spec. All of the
     essential information on the parameters of the channel will be in the
     ChannelML file, this file is used by neuroConstruct to make that data
     more user friendly
 -->

<cmlmetadata xmlns="http://www.neuroConstruct.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.neuroConstruct.org ChannelMLMetadata.xsd">

    <parameter>
        <parameterpath>channelml/channel_type/current_voltage_relation/ohmic/conductance/@default_gmax</parameterpath>
        <alias>gmax</alias>
        <description>Maximum Conductance Density</description>
    </parameter>

    <parameter>
        <parameterpath>channelml/channel_type/current_voltage_relation/ohmic/@default_erev</parameterpath>
        <alias>e</alias>
        <description>Reversal Potential</description>
    </parameter>

    <plot>
        <plotname>Current out of cell</plotname>
        <independentvariable>v</independentvariable>
        <maxvalue>100</maxvalue>
        <minvalue>-100</minvalue>
        <expression>gmax * (v-e)</expression>
    </plot>

</cmlmetadata>
